baseURL = "https://takecian.github.io/"
languageCode = "ja-jp"
title = "takecian"
theme = "hugo-ink"

disqusShortname = ""  # Adding empty Disqus shortname to prevent errors

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/work/work"
    weight = 2
[[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/about"
    weight = 4

[params]
	subtitle = "Diary"

	# Optional 64x64 avatar image.
	avatar = "https://takecian.github.io/images/avatar.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"

[[params.social]]
    name = "RSS"
    icon = "rss"
    url = "/index.xml"

ignoreErrors = ["error-remote-getjson"]
ignoreLogs = ["warning-goldmark-raw-html"]