baseURL = "https://takecian.github.io/"
languageCode = "ja-jp"
title = "takecian"
theme = "hyde-hyde"

googleAnalytics = "UA-32176657-40"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/work/work"
    weight = 2
[[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/about"
    weight = 4
[params.social]
	twitter = "takecian"
	facebook = "takecian"
	github = "takecian"