baseURL = "https://takecian.github.io/"
languageCode = "ja-jp"
title = "takecian"
theme = "hugo-ink"

googleAnalytics = "UA-32176657-40"

[[menu.main]]
    name = "Posts"
    identifier = "posts"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "Work"
    identifier = "work"
    url = "/work/work"
    weight = 2
[[menu.main]]
    name = "Note"
    identifier = "note"
    url = "/note/"
    weight = 3
[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/about"
    weight = 4

[params]
	subtitle = "Crisp, minimal personal [blog theme for Hugo](https://github.com/knadh/hugo-ink)"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"

[[params.social]]
    name = "RSS"
    icon = "rss"
    url = "/index.xml"
